basePath: /
definitions:
  database.CreateUserParams:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  main.ErrorMessage:
    properties:
      error:
        type: string
    type: object
  validator.Validator:
    properties:
      errors:
        items:
          type: string
        type: array
      fieldErrors:
        additionalProperties:
          type: string
        type: object
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: ${HOST}
info:
  contact:
    email: support@swagger.io
    name: John Carlo Asilo
    url: http://www.swagger.io/support
  description: This API is going to provide all infos for the API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API Title
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/database.CreateUserParams'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorMessage'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/validator.Validator'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorMessage'
      summary: Create a new user
      tags:
      - users
schemes:
- ${SCHEMES}
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
