basePath: /
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: ${HOST}
info:
  contact:
    email: jcarloasilo@gmail.com
    name: John Carlo Asilo
    url: http://jcarlo.vercel.app
  description: This API is going to provide all infos for the API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API Title
  version: "1.0"
paths: {}
schemes:
- ${SCHEMES}
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and the token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
